---
# Bootloader configuration
bootLoader: grub
efiBootLoader: grub
kernelLine: ", with Hyprose"
kernelLineFallback: "fallback"
installEFIFallback: true

# GRUB specific
grubInstall: grub-install
grubMkconfig: grub-mkconfig
grubCfg: /boot/grub/grub.cfg
gurbProbe: grub-probe
efiBootMgr: efibootmgr

# Target partition
efiBootLoaderId: "HYPROSE"
installPath: /boot/efi
