---
# Mount configuration
mount:
    - device: "/dev/sda3"
      fsType: "ext4"
      mountPoint: "/"
      options: "defaults,noatime"
    - device: "/dev/sda1"
      fsType: "vfat"
      mountPoint: "/boot/efi"
      options: "defaults,noatime"
