---
# Hyprose Calamares Settings
# Defines the installer flow

instances:
- id:       hyprose
  module:   welcome
  config:   welcome.conf

- id:       hyprose
  module:   locale
  config:   locale.conf

- id:       hyprose
  module:   keyboard
  config:   keyboard.conf

- id:       hyprose
  module:   partition
  config:   partition.conf

- id:       hyprose
  module:   users
  config:   users.conf

- id:       hyprose
  module:   summary
  config:   summary.conf

- id:       hyprose
  module:   mount
  config:   mount.conf

- id:       hyprose
  module:   unpackfs
  config:   unpackfs.conf

- id:       hyprose
  module:   machineid
  config:   machineid.conf

- id:       hyprose
  module:   fstab
  config:   fstab.conf

- id:       hyprose
  module:   shellprocess
  config:   shellprocess.conf

- id:       hyprose
  module:   grubcfg
  config:   grubcfg.conf

- id:       hyprose
  module:   bootloader
  config:   bootloader.conf

- id:       hyprose
  module:   packages
  config:   packages.conf

- id:       hyprose
  module:   umount
  config:   umount.conf

- id:       hyprose
  module:   finished
  config:   finished.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary

- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - shellprocess
  - grubcfg
  - bootloader
  - packages
  - umount

- show:
  - finished
